### ISSUE TITLE
Extensions are not compatible

### ISSUE THREAD

**Issue by subhadippramanik** [eclipse/hawkbit-extensions#25]
Last released tag of `artifact-repository-s3` is `0.2.0M3` which is not compatible anymore with the version `0.2.0` of hawkbit. Please release a compatible tag.

e.g. - `DBArtifact` is changed to `AbstractDBArtifact` in `hawkbit-core` and used by bean org.eclipse.hawkbit.artifact.repository.S3RepositoryAutoConfiguration

**Comment by schabdo** [comment]
In the beginning of HawkBit all extensions were part of the repository `eclipse/hawkbit`. Later on we moved extensions to a new repository (`eclipse/hawkbit-extensions`). So the tag `0.2.0M3` of the S3 extension is referring to these old days were extensions were part of HawkBit. If you'll use `0.2.0M3` tag of HawkBit together with `0.2.0M3` of S3 extension they are compatible.

But I got your point. I can't tell whether we're going to provide milestones and releases for extensions in the near future as well. As for now you could tag the extensions on your own fork.

**Comment by schabdo** [comment]
Closed in favor of #56
